routes/admin.php
<?php


Route::resource('/users', 'UserController');

Route::post('/users/restore', 'UserController@restore');

Route::resource('/posts', 'PostsController');

Route::resource('/tags', 'TagsController');

Route::get('/getTags', 'TagsController@getTags');

Route::get('/', 'DashController@index');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'HomeController@index');

Route::get('/post/{post}', 'HomeController@show');

Route::get('/profile', 'ProfileController@index')->name('profile');

Route::post('/profile', 'ProfileController@store');

Auth::routes();

/*Route::group(['prefix' => 'admin/', 'namespace' => 'Admin', 'middleware' => ['admin']], function(){
	include __DIR__. '/admin.php';
});*/

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;
use Cviebrock\EloquentSluggable\Sluggable;

class Post extends Model
{
    use SoftDeletes, Sluggable;

    protected $fillable = [
    	'title', 'image', 'body', 'user_id'
    ];

    protected $dates = [
    	'deleted_at'
    ];

    /*para buscar por el slug con model binding*/

    public function getRouteKeyName()
    {
        return 'slug';
    }

    /*Mutadores*/

    public function setImageAttribute($image)
    {
    	$name = time().$image->getClientOriginalName();
    	$this->attributes['image'] = $name;
    	\Storage::disk('cover')->put($name, \File::get($image));
    }

    public function setTitleAttribute($value)
    {
    	$this->attributes['title'] = ucfirst($value);
    }

    public function setBodyAttribute($value)
    {
    	$this->attributes['body'] = ucfirst($value);
    }
    /*Comprobar si existe el archivo en el servidor*/
    public function DocumentExist()
    {
    	return \File::exists(public_path('images/cover/').$this->image);
    }
    /*Asignamos url a la imagen*/
    public function getImagePathAttribute()
    {
    	if($this->DocumentExist())
    	{
    		return '/images/cover/'. $this->image;
    	}

    	return '/images/cover/noimage.jpg';
    	
    }

    public function getCommentTextAttribute()
    {
        $count = $this->comments()->count();
        if($count === 0)
        {
            return 'Sin Comentarios';
        }else if($count == 1)
        {
            return '1 Comentario';
        }else{
            return $count. ' Comentarios';
        }

    }


    /*Relaciones*/
    public function editor()
    {
    	return $this->belongsTo(User::class, 'user_id');
    }

    public function comments()
    {
    	return $this->hasMany(Comment::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }


      /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_name', 'first_name', 'last_name', 'section', 'phone','role_id', 'email', 'password',
        'facebook_url', 'twiter_url', 'linkedin_url', 'avatar', 'description',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $dates = [
        'deleted_at'
    ];

    public function getFullNameAttribute()
    {
        return "{$this->first_name} {$this->last_name}";
    }

    public function isDeleted()
    {
        if($this->deleted_at != null)
        {
            return true;
        }
    }

    public function avatarExist()
    {
        return \File::exists(public_path('images/avatar/').$this->avatar);
    }

    public function getAvatarPathAttribute()
    {
        if($this->avatar != null && $this->avatarExist())
        {
            return '/images/avatar/' . $this->avatar;
        }
        return '/images/avatar/user.png';

    }

    /* Mutadores */
    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }

    public function setUserNameAttribute($value)
    {
        $this->attributes['user_name'] = strtolower($value);
    } 

    public function setFirstNameAttribute($value)
    {
        $this->attributes['first_name'] = ucwords(strtolower($value));
    }

    public function setLastNameAttribute($value)
    {
        $this->attributes['last_name'] = ucwords(strtolower($value));
    }   




    /*Relaciones*/

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function skills()
    {
        return $this->belongsToMany(Skill::class);
    }

    /* scopes para filtros */

    public function scopeUserName($query, $userName)
    {
        if(trim($userName) != "")
        {
            $query->where('user_name', 'LIKE', "%$userName%");
        }
    }

    public function scopeFirstName($query, $firstName)
    {
        if(trim($firstName) != "")
        {
            $query->where('first_name','LIKE', "%$firstName%");
        }
    }

    public function scopeLastName($query, $lastName)
    {
        if(trim($lastName) != "")
        {
            $query->where('last_name','LIKE', "%$lastName%");
        }
    }

    public function scopeRole($query, $role)
    {
        if(trim($role) != "" && is_numeric($role))
        {
            $query->where('role_id', $role);
        }   
    }


}

app/Http/Controllers/Admin/PostsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Post;
use App\Tag;
use App\Http\Requests;
use App\Http\Requests\Admin\CreatePostRequest;
use App\Http\Controllers\Controller;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::with('editor')->paginate(10);
        return view('admin.posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags = Tag::orderBy('name')->get();
        return view('admin.posts.create', compact('tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePostRequest $request)
    {
        $post = new Post($request->all());
        $post->user_id = auth()->user()->id;
        $post->save();
        $post->tags()->attach($request->tags);
        return redirect()->route('posts.index')->with('success', 'Se ha creado el post correctamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::findOrFail($id);
        dd($post);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/posts/show.blade.php
@extends('layouts.app')
@section('title', $post->title)
@section('content')
	<div class="container">
		@include('partials.message')
		<div class="col-md-8 col-md-offset-2">
			<div class="title-post">
				<h1>{{ $post->title }}
					@foreach($post->tags as $tag)
						<label class="label label-info">{{$tag->name}}</label>
					@endforeach
					</h1>
				<img src="{{ $post->image_path }}" class="img img-responsive">
			</div>	
			<div class="head-post-autor col-md-12">
				<div class="pull-left">
					{{$post->created_at}}
				</div>
				<div class="pull-right">
					<span  class="badge">
						{{$post->rating}} Visitas
					</span> 
					<span class="badge badge-info">
						{{$post->comment_text}}
					</span>
				</div>
			</div>
			<br>
			<hr class="hr-post">
			<div class="col-md-12">
				{!! $post->body !!}
			</div>
			<div class="col-md-12">
				<div class="media">
		            <a class="pull-left" href="#">
		                <img class="media-object dp img-circle" src="{{ $post->editor->avatar_path }}" style="width: 100px;height:100px;">
		            </a>
		            <div class="media-body">
		                <h4 class="media-heading"> {{$post->editor->full_name }} </h4>
		                <h5>{{ $post->editor->description }}</h5>
		                <hr style="margin:8px auto">

		                <span class="label label-default">HTML5/CSS3</span>
		                <span class="label label-default">jQuery</span>
		                <span class="label label-info">CakePHP</span>
		                <span class="label label-default">Android</span>
		            </div>
		        </div>
			</div>
			@if($post->comments->count() > 0)
			<div class="col-md-12">
				
			</div>	
			@endif
			<div class="col-md-12">
				<div class="panel panel-info">
					<div class="panel-heading">
						<h3 class="panel-title">Dejanos tus comentarios</h3>
					</div>
					<div class="panel-body">
						<form>
							<textarea class="form-control"></textarea>
						</form>
					</div>
					<div class="panel-footer text-center">
						<input type="submit" value="enviar" class="btn btn-info">
					</div>
				</div>
			</div>

		</div>
		
	</div>
@stop